Fixed incorrect indentation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -54,26 +54,26 @@ jobs:
       - image: circleci/python:3.6
     steps:
       - run:
-            name: Setup conda path in env variables
-            command: |
-              echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV
-        - run:
-            name: Create new conda env  # Separate command so if it fails (when using cache) the entire build will not.
-            command: |
-              if conda env list | grep testenv ; then echo "Conda env testenv already exists courtesy of the cache."; else conda create -n testenv -yq; fi
-        - run:
-            name: Install packages in conda env
-            command: |
-              conda install -n testenv python=3.6 numpy scipy scikit-learn matplotlib pandas \
-              flake8 lxml nose cython mkl sphinx coverage patsy boto3 pillow pandas -yq
-              conda install -n testenv nibabel nilearn nose-timer -c conda-forge -yq
-        - run:
-            name: Running CircleCI test (make html)
-            command: |
-              source activate testenv
-              pip install -e .
-              set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
-            no_output_timeout: 5h
+          name: Setup conda path in env variables
+          command: |
+            echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV
+      - run:
+          name: Create new conda env  # Separate command so if it fails (when using cache) the entire build will not.
+          command: |
+            if conda env list | grep testenv ; then echo "Conda env testenv already exists courtesy of the cache."; else conda create -n testenv -yq; fi
+      - run:
+          name: Install packages in conda env
+          command: |
+            conda install -n testenv python=3.6 numpy scipy scikit-learn matplotlib pandas \
+            flake8 lxml nose cython mkl sphinx coverage patsy boto3 pillow pandas -yq
+            conda install -n testenv nibabel nilearn nose-timer -c conda-forge -yq
+      - run:
+          name: Running CircleCI test (make html)
+          command: |
+            source activate testenv
+            pip install -e .
+            set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
+          no_output_timeout: 5h
 
   caching:
     docker:
